# coding: utf-8

"""
    OORT Agent SDK Interface

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import oort_sdk_client
from oort_sdk_client.models.send_file_response import SendFileResponse  # noqa: E501
from oort_sdk_client.rest import ApiException

class TestSendFileResponse(unittest.TestCase):
    """SendFileResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SendFileResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = oort_sdk_client.models.send_file_response.SendFileResponse()  # noqa: E501
        if include_optional :
            return SendFileResponse(
                uuid = '0'
            )
        else :
            return SendFileResponse(
                uuid = '0',
        )

    def testSendFileResponse(self):
        """Test SendFileResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
