# coding: utf-8

"""
    OORT Agent SDK Interface

    Client interface to the OORT agent.  # noqa: E501

    The version of the OpenAPI document: 1.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import oort_sdk_client
from oort_sdk_client.models.adcs_xyz_float_t import AdcsXyzFloatT  # noqa: E501
from oort_sdk_client.rest import ApiException

class TestAdcsXyzFloatT(unittest.TestCase):
    """AdcsXyzFloatT unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AdcsXyzFloatT
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = oort_sdk_client.models.adcs_xyz_float_t.AdcsXyzFloatT()  # noqa: E501
        if include_optional :
            return AdcsXyzFloatT(
                x = 1.337, 
                y = 1.337, 
                z = 1.337
            )
        else :
            return AdcsXyzFloatT(
                x = 1.337,
                y = 1.337,
                z = 1.337,
        )

    def testAdcsXyzFloatT(self):
        """Test AdcsXyzFloatT"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
