# coding: utf-8

"""
    OORT Agent SDK Interface

    Client interface to the OORT agent.  # noqa: E501

    The version of the OpenAPI document: 1.5
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import oort_sdk_client
from oort_sdk_client.api.sdk_api import SdkApi  # noqa: E501
from oort_sdk_client.rest import ApiException


class TestSdkApi(unittest.TestCase):
    """SdkApi unit test stubs"""

    def setUp(self):
        self.api = oort_sdk_client.api.sdk_api.SdkApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_command_adcs(self):
        """Test case for command_adcs

        """
        pass

    def test_get_adcs(self):
        """Test case for get_adcs

        """
        pass

    def test_get_tfrs(self):
        """Test case for get_tfrs

        """
        pass

    def test_query_available_files(self):
        """Test case for query_available_files

        """
        pass

    def test_retrieve_file(self):
        """Test case for retrieve_file

        """
        pass

    def test_send_file(self):
        """Test case for send_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
