# coding: utf-8

"""
    OORT Agent SDK Interface

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import oort_sdk_client
from oort_sdk_client.models.retrieve_file_request import RetrieveFileRequest  # noqa: E501
from oort_sdk_client.rest import ApiException

class TestRetrieveFileRequest(unittest.TestCase):
    """RetrieveFileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RetrieveFileRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = oort_sdk_client.models.retrieve_file_request.RetrieveFileRequest()  # noqa: E501
        if include_optional :
            return RetrieveFileRequest(
                id = '0', 
                save_path = '0'
            )
        else :
            return RetrieveFileRequest(
                id = '0',
                save_path = '0',
        )

    def testRetrieveFileRequest(self):
        """Test RetrieveFileRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
