# coding: utf-8

"""
    OORT Agent SDK Interface

    Client interface to the OORT agent.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import oort_sdk_client
from oort_sdk_client.models.tfrs_response import TfrsResponse  # noqa: E501
from oort_sdk_client.rest import ApiException

class TestTfrsResponse(unittest.TestCase):
    """TfrsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TfrsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = oort_sdk_client.models.tfrs_response.TfrsResponse()  # noqa: E501
        if include_optional :
            return TfrsResponse(
                age = 1.337, 
                utc_time = 56, 
                ecef_pos_x = 1.337, 
                ecef_pos_y = 1.337, 
                ecef_pos_z = 1.337, 
                ecef_vel_x = 1.337, 
                ecef_vel_y = 1.337, 
                ecef_vel_z = 1.337
            )
        else :
            return TfrsResponse(
                age = 1.337,
                utc_time = 56,
                ecef_pos_x = 1.337,
                ecef_pos_y = 1.337,
                ecef_pos_z = 1.337,
                ecef_vel_x = 1.337,
                ecef_vel_y = 1.337,
                ecef_vel_z = 1.337,
        )

    def testTfrsResponse(self):
        """Test TfrsResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
