# coding: utf-8

"""
    OORT Agent SDK Interface

    Client interface to the OORT agent.  # noqa: E501

    The version of the OpenAPI document: 1.5
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from oort_sdk_client.configuration import Configuration


class AdcsCommandRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'command': 'str',
        'aperture': 'str',
        'target': 'AdcsTarget',
        'angle': 'float',
        'vector': 'AdcsXyzFloatT',
        'quat': 'AdcsQuatT'
    }

    attribute_map = {
        'command': 'command',
        'aperture': 'aperture',
        'target': 'target',
        'angle': 'angle',
        'vector': 'vector',
        'quat': 'quat'
    }

    def __init__(self, command=None, aperture=None, target=None, angle=None, vector=None, quat=None, local_vars_configuration=None):  # noqa: E501
        """AdcsCommandRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._command = None
        self._aperture = None
        self._target = None
        self._angle = None
        self._vector = None
        self._quat = None
        self.discriminator = None

        self.command = command
        if aperture is not None:
            self.aperture = aperture
        if target is not None:
            self.target = target
        if angle is not None:
            self.angle = angle
        if vector is not None:
            self.vector = vector
        if quat is not None:
            self.quat = quat

    @property
    def command(self):
        """Gets the command of this AdcsCommandRequest.  # noqa: E501

        SPACS attitude control command  # noqa: E501

        :return: The command of this AdcsCommandRequest.  # noqa: E501
        :rtype: str
        """
        return self._command

    @command.setter
    def command(self, command):
        """Sets the command of this AdcsCommandRequest.

        SPACS attitude control command  # noqa: E501

        :param command: The command of this AdcsCommandRequest.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and command is None:  # noqa: E501
            raise ValueError("Invalid value for `command`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                command is not None and len(command) > 5):
            raise ValueError("Invalid value for `command`, length must be less than or equal to `5`")  # noqa: E501

        self._command = command

    @property
    def aperture(self):
        """Gets the aperture of this AdcsCommandRequest.  # noqa: E501

        Aperture (imager, antenna, etc) name to use in ADCS pointing requests  # noqa: E501

        :return: The aperture of this AdcsCommandRequest.  # noqa: E501
        :rtype: str
        """
        return self._aperture

    @aperture.setter
    def aperture(self, aperture):
        """Sets the aperture of this AdcsCommandRequest.

        Aperture (imager, antenna, etc) name to use in ADCS pointing requests  # noqa: E501

        :param aperture: The aperture of this AdcsCommandRequest.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                aperture is not None and len(aperture) > 24):
            raise ValueError("Invalid value for `aperture`, length must be less than or equal to `24`")  # noqa: E501

        self._aperture = aperture

    @property
    def target(self):
        """Gets the target of this AdcsCommandRequest.  # noqa: E501


        :return: The target of this AdcsCommandRequest.  # noqa: E501
        :rtype: AdcsTarget
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this AdcsCommandRequest.


        :param target: The target of this AdcsCommandRequest.  # noqa: E501
        :type: AdcsTarget
        """

        self._target = target

    @property
    def angle(self):
        """Gets the angle of this AdcsCommandRequest.  # noqa: E501


        :return: The angle of this AdcsCommandRequest.  # noqa: E501
        :rtype: float
        """
        return self._angle

    @angle.setter
    def angle(self, angle):
        """Sets the angle of this AdcsCommandRequest.


        :param angle: The angle of this AdcsCommandRequest.  # noqa: E501
        :type: float
        """

        self._angle = angle

    @property
    def vector(self):
        """Gets the vector of this AdcsCommandRequest.  # noqa: E501


        :return: The vector of this AdcsCommandRequest.  # noqa: E501
        :rtype: AdcsXyzFloatT
        """
        return self._vector

    @vector.setter
    def vector(self, vector):
        """Sets the vector of this AdcsCommandRequest.


        :param vector: The vector of this AdcsCommandRequest.  # noqa: E501
        :type: AdcsXyzFloatT
        """

        self._vector = vector

    @property
    def quat(self):
        """Gets the quat of this AdcsCommandRequest.  # noqa: E501


        :return: The quat of this AdcsCommandRequest.  # noqa: E501
        :rtype: AdcsQuatT
        """
        return self._quat

    @quat.setter
    def quat(self, quat):
        """Sets the quat of this AdcsCommandRequest.


        :param quat: The quat of this AdcsCommandRequest.  # noqa: E501
        :type: AdcsQuatT
        """

        self._quat = quat

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdcsCommandRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AdcsCommandRequest):
            return True

        return self.to_dict() != other.to_dict()
