# coding: utf-8

"""
    OORT Agent SDK Interface

    Client interface to the OORT agent.  # noqa: E501

    The version of the OpenAPI document: 1.3
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from oort_sdk_client.configuration import Configuration


class AdcsResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'mode': 'str',
        'age': 'float',
        'controller': 'str',
        'hk': 'AdcsHk'
    }

    attribute_map = {
        'mode': 'mode',
        'age': 'age',
        'controller': 'controller',
        'hk': 'hk'
    }

    def __init__(self, mode=None, age=None, controller=None, hk=None, local_vars_configuration=None):  # noqa: E501
        """AdcsResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._mode = None
        self._age = None
        self._controller = None
        self._hk = None
        self.discriminator = None

        self.mode = mode
        self.age = age
        if controller is not None:
            self.controller = controller
        if hk is not None:
            self.hk = hk

    @property
    def mode(self):
        """Gets the mode of this AdcsResponse.  # noqa: E501

        The current ADCS mode  # noqa: E501

        :return: The mode of this AdcsResponse.  # noqa: E501
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this AdcsResponse.

        The current ADCS mode  # noqa: E501

        :param mode: The mode of this AdcsResponse.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and mode is None:  # noqa: E501
            raise ValueError("Invalid value for `mode`, must not be `None`")  # noqa: E501

        self._mode = mode

    @property
    def age(self):
        """Gets the age of this AdcsResponse.  # noqa: E501

        Time in seconds since last live reading from ACDS  # noqa: E501

        :return: The age of this AdcsResponse.  # noqa: E501
        :rtype: float
        """
        return self._age

    @age.setter
    def age(self, age):
        """Sets the age of this AdcsResponse.

        Time in seconds since last live reading from ACDS  # noqa: E501

        :param age: The age of this AdcsResponse.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and age is None:  # noqa: E501
            raise ValueError("Invalid value for `age`, must not be `None`")  # noqa: E501

        self._age = age

    @property
    def controller(self):
        """Gets the controller of this AdcsResponse.  # noqa: E501

        the controlling payload at the time of the last live reading  # noqa: E501

        :return: The controller of this AdcsResponse.  # noqa: E501
        :rtype: str
        """
        return self._controller

    @controller.setter
    def controller(self, controller):
        """Sets the controller of this AdcsResponse.

        the controlling payload at the time of the last live reading  # noqa: E501

        :param controller: The controller of this AdcsResponse.  # noqa: E501
        :type: str
        """

        self._controller = controller

    @property
    def hk(self):
        """Gets the hk of this AdcsResponse.  # noqa: E501


        :return: The hk of this AdcsResponse.  # noqa: E501
        :rtype: AdcsHk
        """
        return self._hk

    @hk.setter
    def hk(self, hk):
        """Sets the hk of this AdcsResponse.


        :param hk: The hk of this AdcsResponse.  # noqa: E501
        :type: AdcsHk
        """

        self._hk = hk

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdcsResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AdcsResponse):
            return True

        return self.to_dict() != other.to_dict()
