# coding: utf-8

"""
    OORT Agent SDK Interface

    Client interface to the OORT agent.  # noqa: E501

    The version of the OpenAPI document: 1.3
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from oort_sdk_client.configuration import Configuration


class AvailableFilesResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'files': 'list[FileInfo]',
        'overflow': 'bool'
    }

    attribute_map = {
        'files': 'files',
        'overflow': 'overflow'
    }

    def __init__(self, files=None, overflow=None, local_vars_configuration=None):  # noqa: E501
        """AvailableFilesResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._files = None
        self._overflow = None
        self.discriminator = None

        self.files = files
        if overflow is not None:
            self.overflow = overflow

    @property
    def files(self):
        """Gets the files of this AvailableFilesResponse.  # noqa: E501


        :return: The files of this AvailableFilesResponse.  # noqa: E501
        :rtype: list[FileInfo]
        """
        return self._files

    @files.setter
    def files(self, files):
        """Sets the files of this AvailableFilesResponse.


        :param files: The files of this AvailableFilesResponse.  # noqa: E501
        :type: list[FileInfo]
        """
        if self.local_vars_configuration.client_side_validation and files is None:  # noqa: E501
            raise ValueError("Invalid value for `files`, must not be `None`")  # noqa: E501

        self._files = files

    @property
    def overflow(self):
        """Gets the overflow of this AvailableFilesResponse.  # noqa: E501

        true if there are more files available than could be returned in this call  # noqa: E501

        :return: The overflow of this AvailableFilesResponse.  # noqa: E501
        :rtype: bool
        """
        return self._overflow

    @overflow.setter
    def overflow(self, overflow):
        """Sets the overflow of this AvailableFilesResponse.

        true if there are more files available than could be returned in this call  # noqa: E501

        :param overflow: The overflow of this AvailableFilesResponse.  # noqa: E501
        :type: bool
        """

        self._overflow = overflow

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AvailableFilesResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AvailableFilesResponse):
            return True

        return self.to_dict() != other.to_dict()
