# coding: utf-8

"""
    OORT Agent SDK Interface

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from oort_sdk_client.configuration import Configuration


class FileInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'path': 'str',
        'size': 'int',
        'modified': 'int',
        'created': 'int',
        'crc32': 'str'
    }

    attribute_map = {
        'id': 'id',
        'path': 'path',
        'size': 'size',
        'modified': 'modified',
        'created': 'created',
        'crc32': 'crc32'
    }

    def __init__(self, id=None, path=None, size=None, modified=None, created=None, crc32=None, local_vars_configuration=None):  # noqa: E501
        """FileInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._path = None
        self._size = None
        self._modified = None
        self._created = None
        self._crc32 = None
        self.discriminator = None

        self.id = id
        self.path = path
        self.size = size
        self.modified = modified
        self.created = created
        self.crc32 = crc32

    @property
    def id(self):
        """Gets the id of this FileInfo.  # noqa: E501


        :return: The id of this FileInfo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FileInfo.


        :param id: The id of this FileInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def path(self):
        """Gets the path of this FileInfo.  # noqa: E501


        :return: The path of this FileInfo.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this FileInfo.


        :param path: The path of this FileInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and path is None:  # noqa: E501
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path

    @property
    def size(self):
        """Gets the size of this FileInfo.  # noqa: E501


        :return: The size of this FileInfo.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this FileInfo.


        :param size: The size of this FileInfo.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and size is None:  # noqa: E501
            raise ValueError("Invalid value for `size`, must not be `None`")  # noqa: E501

        self._size = size

    @property
    def modified(self):
        """Gets the modified of this FileInfo.  # noqa: E501


        :return: The modified of this FileInfo.  # noqa: E501
        :rtype: int
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """Sets the modified of this FileInfo.


        :param modified: The modified of this FileInfo.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and modified is None:  # noqa: E501
            raise ValueError("Invalid value for `modified`, must not be `None`")  # noqa: E501

        self._modified = modified

    @property
    def created(self):
        """Gets the created of this FileInfo.  # noqa: E501


        :return: The created of this FileInfo.  # noqa: E501
        :rtype: int
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this FileInfo.


        :param created: The created of this FileInfo.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and created is None:  # noqa: E501
            raise ValueError("Invalid value for `created`, must not be `None`")  # noqa: E501

        self._created = created

    @property
    def crc32(self):
        """Gets the crc32 of this FileInfo.  # noqa: E501


        :return: The crc32 of this FileInfo.  # noqa: E501
        :rtype: str
        """
        return self._crc32

    @crc32.setter
    def crc32(self, crc32):
        """Sets the crc32 of this FileInfo.


        :param crc32: The crc32 of this FileInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and crc32 is None:  # noqa: E501
            raise ValueError("Invalid value for `crc32`, must not be `None`")  # noqa: E501

        self._crc32 = crc32

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FileInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FileInfo):
            return True

        return self.to_dict() != other.to_dict()
