# coding: utf-8

"""
    OORT Agent SDK Interface

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from oort_sdk_client.configuration import Configuration


class SendFileRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'destination': 'str',
        'filepath': 'str',
        'topic': 'str',
        'options': 'SendOptions'
    }

    attribute_map = {
        'destination': 'destination',
        'filepath': 'filepath',
        'topic': 'topic',
        'options': 'options'
    }

    def __init__(self, destination=None, filepath=None, topic=None, options=None, local_vars_configuration=None):  # noqa: E501
        """SendFileRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._destination = None
        self._filepath = None
        self._topic = None
        self._options = None
        self.discriminator = None

        self.destination = destination
        self.filepath = filepath
        self.topic = topic
        if options is not None:
            self.options = options

    @property
    def destination(self):
        """Gets the destination of this SendFileRequest.  # noqa: E501

        the destination to send the file to  # noqa: E501

        :return: The destination of this SendFileRequest.  # noqa: E501
        :rtype: str
        """
        return self._destination

    @destination.setter
    def destination(self, destination):
        """Sets the destination of this SendFileRequest.

        the destination to send the file to  # noqa: E501

        :param destination: The destination of this SendFileRequest.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and destination is None:  # noqa: E501
            raise ValueError("Invalid value for `destination`, must not be `None`")  # noqa: E501

        self._destination = destination

    @property
    def filepath(self):
        """Gets the filepath of this SendFileRequest.  # noqa: E501

        the source filepath  # noqa: E501

        :return: The filepath of this SendFileRequest.  # noqa: E501
        :rtype: str
        """
        return self._filepath

    @filepath.setter
    def filepath(self, filepath):
        """Sets the filepath of this SendFileRequest.

        the source filepath  # noqa: E501

        :param filepath: The filepath of this SendFileRequest.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and filepath is None:  # noqa: E501
            raise ValueError("Invalid value for `filepath`, must not be `None`")  # noqa: E501

        self._filepath = filepath

    @property
    def topic(self):
        """Gets the topic of this SendFileRequest.  # noqa: E501

        the pipeline topic to send the file to  # noqa: E501

        :return: The topic of this SendFileRequest.  # noqa: E501
        :rtype: str
        """
        return self._topic

    @topic.setter
    def topic(self, topic):
        """Sets the topic of this SendFileRequest.

        the pipeline topic to send the file to  # noqa: E501

        :param topic: The topic of this SendFileRequest.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and topic is None:  # noqa: E501
            raise ValueError("Invalid value for `topic`, must not be `None`")  # noqa: E501

        self._topic = topic

    @property
    def options(self):
        """Gets the options of this SendFileRequest.  # noqa: E501


        :return: The options of this SendFileRequest.  # noqa: E501
        :rtype: SendOptions
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this SendFileRequest.


        :param options: The options of this SendFileRequest.  # noqa: E501
        :type: SendOptions
        """

        self._options = options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SendFileRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SendFileRequest):
            return True

        return self.to_dict() != other.to_dict()
